In [1]:
import numpy as np    # numpy kütüphanesi eklendi np adında

## Numpy array 


In [2]:
benimListem = [10,20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([10, 20, 30, 40])

In [7]:
type(np.array(benimListem))  # numpyın içerisinden türüyen nesne

numpy.ndarray

In [9]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [10]:
type(matrixListesi)

list

In [11]:
matrixListesi[1][0]

20

In [14]:
np.array(matrixListesi)   #numpy arrayine dönüştü

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [15]:
list(range(0,10))  # 0 ile 10 arasında sayılardan oluşan liste yapar

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0,10)    # 0 ile 10 arasında sayılardan oluşan numpy listesi yapar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)  #(0danbaşla,10akadar,2 şer atlayarak) numpy listesi oluşturdu

array([0, 2, 4, 6, 8])

## zeros  0 oluşturur


In [21]:
np.zeros(5)   # 5 elemanlı 0 listesi oluşturdu

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,2))  #2 ye 2lik 0 matrisi oluşturdu

array([[0., 0.],
       [0., 0.]])

In [23]:
np.ones(5)    # 5tane 5ler listesi oluşturdu

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((9,9))  #9'a 9'luk 1'ler matrisi oluşturur

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace  : eşit olarak aralıklı dizi oluşturur

In [25]:
np.linspace(0,20,5)  #(0ile,20arasında,5 tane eşit dağıtılmış) numpy listesi oluşturur

array([ 0.,  5., 10., 15., 20.])

In [26]:
np.linspace(0,10,20)   # (0 ile , 10 arasında, 20 tane eşit dağıtılmış rakam listesi oluştur)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [27]:
np.eye(10)  #matris oluşturur soldan sağ köşesi 1 diğerleri 0 olan numpy listesi oluşturu

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random kütüphanesi rastgele bazı değerle çıkartır normal standart distrübüsyona göre

In [28]:
np.random.randn(8)

array([ 0.68377882, -0.25498608, -0.567555  ,  0.0562798 ,  0.7262233 ,
       -1.00975573,  0.478226  ,  0.30463466])

In [2]:
np.random.randint(1,10)



NameError: name 'np' is not defined

In [3]:
np.random.randn(4)

NameError: name 'np' is not defined