In [5]:
import numpy as np    # numpy kütüphanesi eklendi np adında

## Numpy array 


In [6]:
benimListem = [10,20,30,40]

In [7]:
type(benimListem)

list

In [8]:
np.array(benimListem)

array([10, 20, 30, 40])

In [9]:
type(np.array(benimListem))  # numpyın içerisinden türüyen nesne

numpy.ndarray

In [10]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [11]:
type(matrixListesi)

list

In [12]:
matrixListesi[1][0]

20

In [13]:
np.array(matrixListesi)   #numpy arrayine dönüştü

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [14]:
list(range(0,10))  # 0 ile 10 arasında sayılardan oluşan liste yapar

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10)    # 0 ile 10 arasında sayılardan oluşan numpy listesi yapar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)  #(0danbaşla,10akadar,2 şer atlayarak) numpy listesi oluşturdu

array([0, 2, 4, 6, 8])

## zeros  0 oluşturur


In [17]:
np.zeros(5)   # 5 elemanlı 0 listesi oluşturdu

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,2))  #2 ye 2lik 0 matrisi oluşturdu

array([[0., 0.],
       [0., 0.]])

In [19]:
np.ones(5)    # 5tane 1ler listesi oluşturdu

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((9,9))  #9'a 9'luk 1'ler matrisi oluşturur

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace  : eşit olarak aralıklı dizi oluşturur

In [21]:
np.linspace(0,20,5)  #(0ile,20arasında,5 tane eşit dağıtılmış) numpy listesi oluşturur

array([ 0.,  5., 10., 15., 20.])

In [22]:
np.linspace(0,10,20)   # (0 ile , 10 arasında, 20 tane eşit dağıtılmış rakam listesi oluştur)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [23]:
np.eye(10)  #matris oluşturur soldan sağ köşesi 1 diğerleri 0 olan numpy listesi oluşturu

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random kütüphanesi rastgele bazı değerle çıkartır normal standart distrübüsyona göre

In [24]:
np.random.randn(8)

array([ 1.01093614,  0.69549501, -0.46860914,  0.47159039,  2.33265023,
        0.31033461,  0.25327448, -1.07618542])

In [25]:
np.random.randint(1,10)



3

In [26]:
np.random.randn(4)

array([-0.49172587,  0.0254592 , -0.7967874 ,  1.41555744])

In [27]:
np.random.randint(1,10,5)

array([8, 6, 1, 4, 6])

In [28]:
np.random.randint(1,300,5)

array([124, 127,  99, 114,  27])

In [29]:
benimNumpyDizim = np.arange(30)

In [30]:
benimRandomDizim = np.random.randint(0,100,30)

In [31]:
benimRandomDizim

array([73, 39, 39, 27, 17, 51, 54, 38, 40, 35, 88, 78, 84, 49, 78, 73, 86,
       58, 19, 68, 68,  5, 39, 57, 22, 41,  2,  5, 22, 76])

In [32]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Numpy dizi methodları

In [34]:
benimNumpyDizim.reshape(5,6) # reshape dönüştür matrise

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
benimNumpyDizim.reshape(6,5) #reshape dönüştür matrise

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
benimNumpyDizim.max() #Dizide en büyük max olan elemanı getirir.

29

In [38]:
benimRandomDizim.max()

88

In [39]:
benimRandomDizim.min() # dizide en küçük eleman min olanı getirir.

2

In [40]:
benimRandomDizim.argmax() #jaçıncı indekste oldunu söyler

10

In [41]:
benimRandomDizim.argmin()

26

In [44]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [47]:
reshapeDizim.shape # güncel dizinin şeklini verir

(5, 6)