In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]) 

In [5]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5 #dizide belli aralığa -5 ekle

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi = np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi=baskaDizi[4:9]

In [12]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [13]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
slicingDizisi[:] = 700

In [15]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [16]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [17]:
ornekDizi = np.arange(0,24)

In [18]:
ornekDiziKopyasi = ornekDizi.copy()

In [19]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyaSlicing=ornekDiziKopyasi[3:6]

In [22]:
ornekDiziKopyaSlicing[:] = 800

In [23]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [24]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [25]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix


In [26]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [27]:
benimMatrixDizim = np.array(benimListem)

In [28]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [29]:
benimMatrixDizim[0]

array([10, 20, 30])

In [30]:
benimMatrixDizim[1][2]

40

In [31]:
benimMatrixDizim[1,2]

40

In [32]:
benimMatrixDizim[2:,1]

array([50])

In [33]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [34]:
benimMatrixDizim[2:,2:]

array([[60]])

In [35]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [36]:
yeniMatrix = np.array(yeniListe)

In [37]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
yeniMatrix[[0,2,3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Operasyonlar


In [45]:
yeniBirDizi = np.random.randint(1,100,20)

In [46]:
yeniBirDizi

array([48, 57, 15, 95, 11, 58, 58, 40, 31, 22, 63, 52, 66, 53, 84, 97, 34,
       39, 11, 61])

In [47]:
yeniBirDizi>24

array([ True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [48]:
sonucDizisi = yeniBirDizi>24

In [49]:
sonucDizisi

array([ True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [50]:
yeniBirDizi[sonucDizisi]

array([48, 57, 95, 58, 58, 40, 31, 63, 52, 66, 53, 84, 97, 34, 39, 61])

In [51]:
yeniBirDizi[yeniBirDizi>24]

array([48, 57, 95, 58, 58, 40, 31, 63, 52, 66, 53, 84, 97, 34, 39, 61])

In [52]:
sonDizi = np.arange(0,24)

In [53]:
sonDizi 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [55]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [56]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [57]:
sonDizi/sonDizi

C:\Users\btk02\AppData\Local\Temp\ipykernel_5500\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
np.sqrt(sonDizi) #karekökünü alır

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [59]:
np.max(sonDizi)

23

In [60]:
np.min(sonDizi)

0

In [61]:
dağılım=np.random.exponential(size=1000)

In [62]:
dağılım

array([7.90492463e-01, 5.93748063e-01, 3.68295824e-01, 6.16058193e-01,
       1.33082962e+00, 8.47310717e-02, 1.52978048e-01, 1.69373229e+00,
       3.25150660e+00, 5.16081290e-01, 3.16784363e-02, 2.51269054e-01,
       1.16249552e-01, 1.99069464e+00, 2.60978973e+00, 1.05076746e+00,
       1.13267421e+00, 2.77569371e+00, 3.34051240e-01, 5.34190735e-01,
       5.12807075e-01, 6.37869067e-01, 1.48462507e+00, 4.52916632e-01,
       7.14980373e-01, 1.86599813e+00, 1.64354426e+00, 1.80210241e+00,
       3.91307463e-01, 8.68754366e-01, 6.24555293e-01, 1.40055563e-01,
       1.68038330e+00, 4.49483092e-01, 4.93242692e-01, 2.17191880e-02,
       1.46589906e+00, 7.43239740e-01, 2.27592756e+00, 2.95042037e-01,
       5.67809383e-01, 6.44335824e-01, 1.66087340e+00, 2.81745308e-01,
       2.22627663e-01, 3.23037193e-02, 2.69490654e+00, 1.14641420e+00,
       2.89313686e+00, 3.09006712e+00, 3.39809025e-01, 2.62615478e-02,
       4.01440456e+00, 1.73461096e+00, 1.79384139e-01, 4.56928457e-01,
      

In [64]:
dağılım2 = np.random.normal(3,1,size=1000)

In [65]:
dağılım3 = np.random.uniform(0,10,100)


In [66]:
dağılım2

array([ 2.08579869,  4.46766227,  2.85996931,  2.63779382,  4.09715854,
        3.6186223 ,  2.49075882,  4.80047194,  3.27298456,  2.95732919,
        3.4020217 ,  4.57689072,  3.31547342,  2.25965064,  5.1664376 ,
        2.11767787,  4.13484092,  2.78497685,  5.38185607,  3.18529352,
        2.61625629,  2.68262533,  3.48793805,  0.98115276,  2.82057934,
        2.29898836,  2.85757517,  4.37004631,  2.09248564,  4.57420505,
        2.97858868,  2.74974068,  4.23496716,  3.19093735,  0.42463393,
        3.10255051,  3.59309084,  1.74331548,  4.3061975 ,  2.22732742,
        4.2061336 ,  4.02750687,  1.94514711,  1.45119718,  4.31489216,
        3.26554114,  4.67150192,  3.91209738,  1.67026913,  3.65599594,
        4.69813024,  2.27849928,  2.33461281,  2.60903463,  3.40112559,
        3.88034328,  1.47128849,  4.14850763,  3.69387184,  2.98089135,
        1.97261574,  3.36617492,  1.90532683,  3.2501618 ,  2.9852739 ,
        2.55239508,  2.53534937,  3.81520771,  1.30013013,  3.94

In [67]:
dağılım3

array([8.85722467, 2.81667697, 2.37970681, 0.70098917, 5.96552105,
       0.36536175, 5.08558943, 9.72210166, 8.90876029, 7.64151821,
       3.77206404, 1.24012187, 5.6682072 , 7.17551522, 8.06121413,
       1.83285315, 2.00148854, 3.50933002, 7.98939177, 3.24988867,
       1.79167241, 9.14691891, 1.01058781, 7.31070182, 9.35497011,
       4.6151642 , 8.89095782, 7.18304307, 5.09685011, 5.6501313 ,
       0.46970606, 8.99221871, 5.19052124, 7.07031176, 2.36549877,
       6.29336072, 1.68937641, 4.18770495, 5.20096902, 6.71164254,
       3.81521751, 2.82483742, 8.84802082, 7.95741308, 3.27462204,
       6.704253  , 6.52318418, 8.81771492, 9.56248542, 7.88679282,
       6.26102297, 9.31477168, 2.43009507, 8.5196512 , 9.32178384,
       2.8815223 , 0.68499011, 5.94256615, 7.05615793, 0.54558809,
       5.28379476, 4.23814994, 4.07441787, 6.89787723, 2.35622281,
       5.09104692, 9.26826378, 2.35667004, 8.95302338, 4.65025684,
       5.77370576, 5.43056078, 4.47126061, 3.15902103, 4.88766

In [68]:
ordered_dist = np.linspace(0,100,20)

In [69]:
ordered_dist

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])